// <auto-generated />
using System;
using CagnotteSolidaire.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CagnotteSolidaire.Infrastructure.Migrations
{
    [DbContext(typeof(CagnotteDbContext))]
    partial class CagnotteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Association", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroRNA")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroRNA")
                        .IsUnique();

                    b.ToTable("Associations");
                });

            modelBuilder.Entity("CagnotteSolidaire.Domain.Entities.Cagnotte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.ToTable("Cagnottes");
                });

            modelBuilder.Entity("Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CagnotteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CagnotteId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeUtilisateur")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("TypeUtilisateur").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CagnotteSolidaire.Domain.Entities.Gestionnaire", b =>
                {
                    b.HasBaseType("Utilisateur");

                    b.Property<Guid>("AssociationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("Gestionnaire");
                });

            modelBuilder.Entity("CagnotteSolidaire.Domain.Entities.Participant", b =>
                {
                    b.HasBaseType("Utilisateur");

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("CagnotteSolidaire.Domain.Entities.Cagnotte", b =>
                {
                    b.HasOne("Association", "Association")
                        .WithMany()
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CagnotteSolidaire.Domain.ValueObjects.Money", "MontantActuel", b1 =>
                        {
                            b1.Property<Guid>("CagnotteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MontantActuel");

                            b1.HasKey("CagnotteId");

                            b1.ToTable("Cagnottes");

                            b1.WithOwner()
                                .HasForeignKey("CagnotteId");
                        });

                    b.OwnsOne("CagnotteSolidaire.Domain.ValueObjects.Money", "Objectif", b1 =>
                        {
                            b1.Property<Guid>("CagnotteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Objectif");

                            b1.HasKey("CagnotteId");

                            b1.ToTable("Cagnottes");

                            b1.WithOwner()
                                .HasForeignKey("CagnotteId");
                        });

                    b.Navigation("Association");

                    b.Navigation("MontantActuel")
                        .IsRequired();

                    b.Navigation("Objectif")
                        .IsRequired();
                });

            modelBuilder.Entity("Participation", b =>
                {
                    b.HasOne("CagnotteSolidaire.Domain.Entities.Cagnotte", null)
                        .WithMany("Participations")
                        .HasForeignKey("CagnotteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CagnotteSolidaire.Domain.ValueObjects.Money", "Montant", b1 =>
                        {
                            b1.Property<Guid>("ParticipationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Montant");

                            b1.HasKey("ParticipationId");

                            b1.ToTable("Participations");

                            b1.WithOwner()
                                .HasForeignKey("ParticipationId");
                        });

                    b.Navigation("Montant")
                        .IsRequired();
                });

            modelBuilder.Entity("Utilisateur", b =>
                {
                    b.OwnsOne("CagnotteSolidaire.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UtilisateurId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("UtilisateurId");

                            b1.ToTable("Utilisateurs");

                            b1.WithOwner()
                                .HasForeignKey("UtilisateurId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("CagnotteSolidaire.Domain.Entities.Cagnotte", b =>
                {
                    b.Navigation("Participations");
                });
#pragma warning restore 612, 618
        }
    }
}
